In [7]:
from urllib.request import urlopen as ureq
from bs4 import BeautifulSoup as soup
import pandas as pd
myurl = 'https://www.yellowpages.com/chicago-il/mip/cafe-il-cortile-8731718#reviews'
open = ureq(myurl)
pagehtml = open.read()
open.close()
pagesoup = soup(pagehtml, "lxml")

c_name = []
c_n = pagesoup.h1.text
c_name.append(c_n)

In [8]:
item = []
for i in pagesoup.find_all(class_='title-price'):
    x = i.text.replace(u'\xa0', u' ')
    item.append(x)

In [9]:
rate = []
r = pagesoup.find(class_='count').text
rate.append(r)

In [10]:
ocr = []
for i in pagesoup.find_all(class_='cross-links'):
    h = i.text
    ocr.append(h)

In [11]:
al = []

info = pagesoup.find_all('dl')

for re in info[0].find_all('dt'):
    al.append(re.text.replace(u'\xa0', u' '))
bl = []
for i in info[0].find_all('dd'):
    bl.append(i.text.replace(u'\xa0', u' '))
al_bl = []
for x,y in zip(al,bl):
    al_bl.append({'info tittle':x,'detail info':y})

In [12]:
sm = []
for i in pagesoup.find_all(class_='smart-article'):
    h = i.text
sm.append(h)

In [13]:
ca = pd.DataFrame({'cafe name':c_name})
ab = pd.DataFrame (al_bl)
mn = pd.DataFrame({'menu':item})
rs = pd.DataFrame({'cafe rating':rate})
oc = pd.DataFrame({'other cafe and restaurants':ocr})
sms = pd.DataFrame({'smart articals':sm})
df = pd.concat([ca,ab,mn,rs,oc,sms],axis=1)
df.to_csv('cafe_mod.csv',encoding = 'utf-8',header=True)

,cafe name,info tittle,detail info,menu,cafe rating,other cafe and restaurants,smart articals
0,Cafe Il Cortile,Hours,Regular HoursMon - Thu:9:00 am - 12:30 pmFri -...,Baked Clams (6) $6.50,(1 Review),Places Near Chicago with Coffee ShopsWrigleyvi...,"If you're craving some coffee in Chicago, then..."
1,NaN,Extra Phones,Primary Phone: (773) 625-2169Phone: (773) 625-...,Fried Calamari $8.95,NaN,More Types of Restaurants in ChicagoHawaiian R...,NaN
2,NaN,Payment method,all major credit cards,Grilled Calamari $9.95,NaN,NaN,NaN
3,NaN,Price Range,$,Cheese $4.50,NaN,NaN,NaN
4,NaN,Neighborhood,Schorsch Forest View,Sausage $4.75,NaN,NaN,NaN
5,NaN,AKA,Cafe II Cortile,Mushrooms $4.75,NaN,NaN,NaN
6,NaN,Other Links,https://www.cafeilcortilemenu.comhttp://cafeco...,Panelli $3.75,NaN,NaN,NaN
7,NaN,Categories,"Coffee Shops, Italian Restaurants, Restaurants",Arancini $3.50,NaN,NaN,NaN
8,NaN,Other Information,Wi-Fi: NoBike Parking: YesAttire: CasualWheelc...,Chicken Livers $6.95,NaN,NaN,NaN
9,NaN,NaN,NaN,Italian Beef w/ Fries $4.00,NaN,NaN,NaN
10,NaN,NaN,NaN,Cheese Beef w/ Fries $4.95,NaN,NaN,NaN
11,NaN,NaN,NaN,Italian Sausage w/ Fries $3.95,NaN,NaN,NaN
12,NaN,NaN,NaN,Grilled Chicken Salad $5.95,NaN,NaN,NaN
13,NaN,NaN,NaN,Chicken Caesar Salad $7.95,NaN,NaN,NaN
14,NaN,NaN,NaN,Tuna Salad $5.95,NaN,NaN,NaN